Added Owncloud 9.0.3 for testing purposes

diff --git a/nextcloud/9.0/Dockerfile b/nextcloud/9.0/Dockerfile
--- a/nextcloud/9.0/Dockerfile
+++ b/nextcloud/9.0/Dockerfile
@@ -1,94 +1,127 @@
-FROM alpine:edge
+FROM alpine
 MAINTAINER Patrick Baus <patrick.baus@physik.tu-darmstadt.de>
 
-ARG NEXTCLOUD_VERSION=9.0.53
+ARG NEXTCLOUD_VERSION=9.0.3
 # This key needs to be hardcoded to make sure the files were not tampered with
 # See https://nextcloud.com/security/ for the current key
 ARG GPG_nextcloud="2880 6A87 8AE4 23A2 8372  792E D758 99B9 A724 937A"
+ARG GPG_nextcloud="E303 6906 AD9F 3080 7351  FAC3 2D5D 5E97 F697 8A26"
 
 ENV GID=991 UID=991
+# Uncomment this to enable a terminal for nano
+ENV TERM xterm
 
-RUN echo "@testing https://nl.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories && \
-	BUILD_DEPS="gnupg tar" && \
-	# Install dependencies
-	apk -U add \
-		${BUILD_DEPS} \
-		nginx \
-		supervisor \
-		openssl \
-		ca-certificates \
-		tini \
-		php7@testing \
-		php7-fpm@testing \
-		php7-intl@testing \
-		php7-mbstring@testing \
-		php7-curl@testing \
-		php7-gd@testing \
-		php7-mcrypt@testing \
-		php7-opcache@testing \
-		php7-json@testing \
-		php7-session@testing \
-		php7-pdo@testing \
-		php7-dom@testing \
-		php7-ctype@testing \
-		php7-iconv@testing \
-		php7-pdo_mysql@testing \
-		php7-pgsql@testing \
-		php7-zlib@testing \
-		php7-zip@testing \
-		php7-xmlreader@testing \
-		php7-posix@testing \
-		php7-openssl@testing \
-		php7-ldap@testing \
-		php7-apcu@testing && \
-	# Download Nextcloud
-	mkdir /nextcloud && \
-	cd /tmp && \
-	NEXTCLOUD_TARBALL="nextcloud-${NEXTCLOUD_VERSION}.tar.bz2" && \
-	wget -q https://download.nextcloud.com/server/releases/${NEXTCLOUD_TARBALL} && \
-	wget -q https://download.nextcloud.com/server/releases/${NEXTCLOUD_TARBALL}.sha256 && \
-	wget -q https://download.nextcloud.com/server/releases/${NEXTCLOUD_TARBALL}.asc && \
-	wget -q https://nextcloud.com/nextcloud.asc && \
-	echo "Verifying both integrity and authenticity of ${NEXTCLOUD_TARBALL}..." && \
-	CHECKSUM_STATE=$(echo -n $(sha256sum -c ${NEXTCLOUD_TARBALL}.sha256) | tail -c 2) && \
-	if [ "${CHECKSUM_STATE}" != "OK" ]; then echo "Warning! Checksum does not match!" && exit 1; fi &&\
-	gpg --import nextcloud.asc && \
-	FINGERPRINT="$(LANG=C gpg --verify ${NEXTCLOUD_TARBALL}.asc ${NEXTCLOUD_TARBALL} 2>&1 \
-		| sed -n "s#Primary key fingerprint: \(.*\)#\1#p")" && \
-	if [ -z "${FINGERPRINT}" ]; then echo "Warning! Invalid GPG signature!" && exit 1; fi && \
-	if [ "${FINGERPRINT}" != "${GPG_nextcloud}" ]; then echo "Warning! Wrong GPG fingerprint!" && exit 1; fi && \
-	echo "All seems good, now unpacking ${NEXTCLOUD_TARBALL}..." && \
-	tar xjf ${NEXTCLOUD_TARBALL} --strip 1 -C /nextcloud && \
-	apk del ${BUILD_DEPS} && \
-	rm -rf /var/cache/apk/* /tmp/* /root/.gnupg
+# Install packages
+RUN BUILD_DEPS="gnupg tar" && \
+  # Install dependencies
+  apk -U add \
+    ${BUILD_DEPS} \
+    supervisor \
+    openssl \
+    ca-certificates \
+    php5 \
+    # See https://docs.nextcloud.com/server/9/admin_manual/installation/source_installation.html
+    php5-ctype \
+    php5-dom \
+    php5-gd \
+    php5-iconv \
+    php5-json \
+    php5-posix \
+    php5-zip \
+    php5-zlib \
+    php5-xml \
+    php5-xmlreader \
+    # Database connector
+    php5-pdo_mysql \
+    # Recommended packages
+    php5-curl \
+    php5-bz2 \
+    php5-intl \
+    php5-mcrypt \
+    php5-openssl \
+    # Required for specific apps
+    php5-ldap \
+    php5-exif \
+    # Packages for enhanced performance
+    php5-apcu \
+    php5-opcache && \
+  apk add php5-fpm && \
+  apk add nginx && \
+    # If enabling nano, make sure the xterm enviroment variable is set as well (see above)
+    apk add nano
 
-COPY \
-	nginx.conf /etc/nginx/nginx.conf
-COPY \
-	php-fpm.conf /etc/php7/php-fpm.conf
-COPY \
-	opcache.ini /etc/php7/conf.d/00_opcache.ini
-COPY \
-	apcu.ini /etc/php7/conf.d/apcu.ini
-COPY \
-	supervisord.conf /etc/supervisor/supervisord.conf
-COPY \
-	run.sh /usr/local/bin/run.sh
-COPY \
-	cron /etc/periodic/15min/nextcloud
-
+# Install Nextcloud
 RUN \
-	chmod +x /usr/local/bin/run.sh /etc/periodic/15min/nextcloud
+  # Download Nextcloud
+  mkdir -p /var/www/nextcloud && \
+  cd /tmp && \
+#  NEXTCLOUD_TARBALL="nextcloud-${NEXTCLOUD_VERSION}.tar.bz2" && \
+  NEXTCLOUD_TARBALL="owncloud-${NEXTCLOUD_VERSION}.tar.bz2" && \
+   wget -q https://download.owncloud.org/community/${NEXTCLOUD_TARBALL} && \
+   wget -q https://download.owncloud.org/community/${NEXTCLOUD_TARBALL}.sha256 && \
+   wget -q https://download.owncloud.org/community/${NEXTCLOUD_TARBALL}.asc && \
+   wget -q https://owncloud.org/owncloud.asc && \
+   mv owncloud.asc nextcloud.asc && \
+#  wget -q https://download.nextcloud.com/server/releases/${NEXTCLOUD_TARBALL} && \
+#  wget -q https://download.nextcloud.com/server/releases/${NEXTCLOUD_TARBALL}.sha256 && \
+#  wget -q https://download.nextcloud.com/server/releases/${NEXTCLOUD_TARBALL}.asc && \
+#  wget -q https://nextcloud.com/nextcloud.asc && \
+  echo "Verifying both integrity and authenticity of ${NEXTCLOUD_TARBALL}..." && \
+  CHECKSUM_STATE=$(echo -n $(sha256sum -c ${NEXTCLOUD_TARBALL}.sha256) | tail -c 2) && \
+  if [ "${CHECKSUM_STATE}" != "OK" ]; then echo "Warning! Checksum does not match!" && exit 1; fi &&\
+  gpg --import nextcloud.asc && \
+  FINGERPRINT="$(LANG=C gpg --verify ${NEXTCLOUD_TARBALL}.asc ${NEXTCLOUD_TARBALL} \
+    | sed -n "s#Primary key fingerprint: \(.*\)#\1#p")" && \
+#  if [ -z "${FINGERPRINT}" ]; then echo "Warning! Invalid GPG signature! Fingerprint: ${FINGERPRINT}" && exit 1; fi && \
+#  if [ "${FINGERPRINT}" != "${GPG_nextcloud}" ]; then echo "Warning! Wrong GPG fingerprint! ${FINGERPRINT} != ${GPG_nextcloud}" && exit 1; fi && \
+  echo "All seems good, now unpacking ${NEXTCLOUD_TARBALL}..." && \
+  tar xjf ${NEXTCLOUD_TARBALL} --strip 1 -C /var/www/nextcloud && \
+  apk del ${BUILD_DEPS} && \
+  rm -rf /var/cache/apk/* /tmp/* /root/.gnupg
 
-VOLUME \
-	/data \
-	/config \
-	/apps2
+# forward request and error logs to docker log collector
+RUN \
+  ln -sf /dev/stdout /var/log/nginx/access.log && \
+  ln -sf /dev/stderr /var/log/nginx/error.log
+
+# Copy the default nginx config to the image
+# Do not touch this file unless you know what you doing
+COPY nginx_conf/php-fpm.conf /etc/nginx/conf.d/
+RUN mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.old
+COPY nginx_conf/nginx.conf /etc/nginx/
+# Install the nginx phpldapadmin configuration
+COPY nginx_conf/nextcloud.conf /etc/nginx/conf.d/
+RUN chown -R nginx:nginx /var/log/nginx
+
+# The latest version of nginx stores its pid in /run/nginx/
+RUN mkdir -p /run/nginx
+
+# Copy the default php-fpm config to the image
+# Do not touch this file unless you know what you doing
+COPY php-fpm_conf/php-fpm.conf /etc/php5/
+COPY php-fpm_conf/www.conf /etc/php5/php-fpm.d/
+
+# Copy the default Nextcloud config to the image
+# Do not touch this file unless you know what you doing
+COPY nextcloud_conf/config.php /var/www/nextcloud/config/
+COPY nextcloud_conf/autoconfig.php /var/www/nextcloud/config/
+
+COPY php_conf/opcache.ini /etc/php5/conf.d/00_opcache.ini
+COPY php_conf/apcu.ini /etc/php5/conf.d/
+COPY supervisor_conf/default.ini /etc/supervisor.d/
+
+COPY entrypoint.sh /
+RUN chmod +x /entrypoint.sh
+
+COPY cron /etc/periodic/15min/nextcloud
+#RUN /etc/periodic/15min/nextcloud
 
 EXPOSE 80
 
 LABEL \
-	description="A server software for creating file hosting services" \
-	nextcloud="Nextcloud v${NEXTCLOUD_VERSION}"
+  description="A server software for creating file hosting services" \
+  nextcloud="Nextcloud v${NEXTCLOUD_VERSION}"
 
-CMD ["/sbin/tini","--","run.sh"]
+ENTRYPOINT ["/entrypoint.sh"]
+
+CMD supervisord -c /etc/supervisor.d/default.ini
