Added Nextcloud 31 and removed 29

diff --git a/nextcloud/31.0/Dockerfile b/nextcloud/31.0/Dockerfile
--- a/nextcloud/31.0/Dockerfile
+++ b/nextcloud/31.0/Dockerfile
@@ -1,5 +1,7 @@
-FROM alpine:3.20.3 AS nextcloud-builder
-ARG NEXTCLOUD_VERSION=29.0.7
+FROM alpine:3.21.3 AS base
+
+FROM base AS builder
+ARG NEXTCLOUD_VERSION=31.0.2
 # This key needs to be hardcoded to make sure the files were not tampered with
 # See https://nextcloud.com/security/ for the current key
 ARG GPG_NEXTCLOUD="2880 6A87 8AE4 23A2 8372  792E D758 99B9 A724 937A"
@@ -16,21 +18,22 @@ RUN \
   cd ${temp_dir} && \
   NEXTCLOUD_TARBALL="nextcloud-${NEXTCLOUD_VERSION}.tar.bz2" && \
   echo -ne "Downloading source...\e[0m" && \
+  wget -q https://download.nextcloud.com/server/releases/nextcloud-${NEXTCLOUD_VERSION}.metadata && \
   wget -q https://download.nextcloud.com/server/releases/${NEXTCLOUD_TARBALL} && \
-  wget -q https://download.nextcloud.com/server/releases/${NEXTCLOUD_TARBALL}.sha256 && \
+  wget -q https://download.nextcloud.com/server/releases/${NEXTCLOUD_TARBALL}.sha512 && \
   wget -q https://download.nextcloud.com/server/releases/${NEXTCLOUD_TARBALL}.asc && \
-  if [ $(echo -n $(sha256sum -c "${NEXTCLOUD_TARBALL}.sha256") | tail -c 2) != "OK" ]; then echo -e "Error! Tarball checksum does not match!" && exit 1; fi && \
+  if [ $(echo -n $(sha512sum -c "${NEXTCLOUD_TARBALL}.sha512") | tail -c 2) != "OK" ]; then echo -e "Error! Tarball checksum does not match!" && exit 1; fi && \
   gpg --import /nextcloud_signing_key.asc && \
   gpg --batch --verify "${NEXTCLOUD_TARBALL}.asc" "${NEXTCLOUD_TARBALL}" && \
   echo -ne "Unpacking source...\e[0m" && \
   mkdir /app && \
   tar xjf "${NEXTCLOUD_TARBALL}" --strip 1 -C /app
 
-FROM alpine:3.20.3
+FROM base
 LABEL maintainer="Patrick Baus <patrick.baus@physik.tu-darmstadt.de>"
 
 # Default GID=101, UID=100
-ENV GID=101 UID=100
+ENV GID=102 UID=102
 
 # Upgrade installed packages
 RUN apk --no-cache upgrade
@@ -100,7 +103,7 @@ RUN rm /etc/nginx/http.d/default.conf
 #############
 # Nextcloud #
 #############
-COPY --from=nextcloud-builder /app /var/www/nextcloud/
+COPY --from=builder /app /var/www/nextcloud/
 COPY upgrade_nextcloud.sh /
 RUN chmod +x /upgrade_nextcloud.sh
 
